# netlify.toml
[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

# Auditoría MÓVIL (Google mobile-first)
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    # URL a auditar (reemplaza "urls")
    audit_url = "/"
    
    # Directorio donde guardar reportes
    output_path = "reports/lighthouse"
    
    # Auditorías específicas a ejecutar
    audits = ["performance", "accessibility", "best-practices", "seo"]
    
    # Umbrales de puntuación (mantiene la misma estructura)
    [plugins.inputs.thresholds]
      performance = 80
      accessibility = 90
      best-practices = 85
      seo = 90

# Configuración de headers para archivos JavaScript
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/src/scripts/*.js"
  [headers.values]
    Content-Type = "text/javascript"

# Configuración específica para archivos de módulos ES6
[[headers]]
  for = "**/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# Headers de seguridad adicionales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Configuración de redirects - sintaxis corregida
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200