# netlify.toml
[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

# Configuración específica para funciones
[functions]
  directory = "netlify/functions"

# Auditoría MÓVIL (Google mobile-first)
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "reports/lighthouse-mobile"
    urls = ["/"]
    
    # Configuración móvil - sintaxis TOML correcta
    [plugins.inputs.settings]
      preset = "mobile"
      formFactor = "mobile"
      onlyCategories = ["performance", "accessibility", "best-practices", "seo"]
    
    # Umbrales más permisivos para móvil (conexiones más lentas)
    [plugins.inputs.thresholds]
      performance = 75
      accessibility = 90
      best-practices = 80
      seo = 85

# Auditoría DESKTOP
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "reports/lighthouse-desktop"
    urls = ["/"]
    
    # Configuración desktop - sintaxis TOML correcta
    [plugins.inputs.settings]
      preset = "desktop"
      formFactor = "desktop"
      onlyCategories = ["performance", "accessibility", "best-practices", "seo"]
    
    # Umbrales más estrictos para desktop (mejores conexiones)
    [plugins.inputs.thresholds]
      performance = 85
      accessibility = 90
      best-practices = 85
      seo = 90

# Configuración de headers para archivos JavaScript
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/src/scripts/*.js"
  [headers.values]
    Content-Type = "text/javascript"

# Configuración específica para archivos de módulos ES6
[[headers]]
  for = "**/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# Headers de seguridad adicionales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Configuración de redirects - sintaxis corregida
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200